#!/usr/bin/env bash
set -euo pipefail

wallpaper="$HOME/.config/x11qtile/wallpapers/fog_forest_2.png"

feh --bg-fill "$wallpaper"
wal -b 232A2E -i "$wallpaper" || true
qtile cmd-obj -o cmd -f restart || true
