#!/usr/bin/env bash
set -euo pipefail

wallpaper="$HOME/.config/x11qtile/wallpapers/claudio-testa-FrlCwXwbwkk-unsplash.jpg"

feh --bg-fill "$wallpaper"
wal -i "$wallpaper" || true
qtile cmd-obj -o cmd -f restart || true
